# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apikey', models.CharField(max_length=48, unique=True)),
                ('naziv', models.CharField(max_length=30)),
                ('adresa', models.GenericIPAddressField(unpack_ipv4=True)),
                ('port', models.IntegerField()),
                ('opis', models.TextField()),
                ('datum_kreiranja', models.DateField()),
                ('demo_video', models.CharField(blank=True, max_length=200, null=True)),
                ('broj_pregleda', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Eksperiment',
                'verbose_name_plural': 'Eksperimenti',
            },
        ),
    ]
