# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apikey', models.CharField(default='7638KUBL24Q9OQDHeRUp4NuD2javwk1t9SzuVrh1RPHQrRqB', max_length=48)),
                ('naziv', models.CharField(max_length=30)),
                ('adresa', models.GenericIPAddressField(unpack_ipv4=True)),
                ('port', models.IntegerField()),
                ('opis', models.TextField()),
                ('datum_kreiranja', models.DateField()),
            ],
        ),
    ]
