# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='apikey',
            field=models.CharField(default='C7LISV27VF4C0JJ6TgBMOsLMbXrEYPP3IpbunV01xuB3YeSi', max_length=48),
        ),
    ]
