# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_tokeni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokeni',
            name='endVreme',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tokeni',
            name='startVreme',
            field=models.DateTimeField(),
        ),
    ]
