# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 17:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interface', '0004_pravapristupa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poruke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sadrzaj', models.TextField()),
                ('odgovor', models.BooleanField(default=False)),
                ('datum_slanja', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Poruka',
                'verbose_name_plural': 'Poruke',
            },
        ),
        migrations.AlterModelOptions(
            name='pravapristupa',
            options={'verbose_name': 'Pravo pristupa', 'verbose_name_plural': 'Prava pristupa'},
        ),
        migrations.AlterModelOptions(
            name='tokeni',
            options={'verbose_name': 'Token', 'verbose_name_plural': 'Tokeni'},
        ),
    ]
